-- MySQL Script generated by MySQL Workbench
-- Sat Feb 22 14:34:00 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `maxEmailsPerMonth` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comp` (
  `idComp` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idComp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CompList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CompList` (
  `idCompList` INT NOT NULL,
  `idUser` INT NULL,
  `idComp` INT NULL,
  PRIMARY KEY (`idCompList`),
  INDEX `idUser_idx` (`idUser` ASC) VISIBLE,
  INDEX `idComp_idx` (`idComp` ASC) VISIBLE,
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idComp`
    FOREIGN KEY (`idComp`)
    REFERENCES `mydb`.`Comp` (`idComp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
